/**
 * src/components/reports/ReportHistoryTable.jsx
 * Archive of all generated reports with download, delete, status badges.
 */
import React, { useState } from "react";
import { Download, Trash2, Loader2, FileText, FileSpreadsheet, AlertCircle } from "lucide-react";
import { formatFileSize, formatRelativeTime } from "../../utils/formatters";

const TYPE_LABELS = {
  executive_summary: "Executive Summary", query_analytics: "Query Analytics",
  upload_report: "Upload Report", workflow_report: "Workflow Report",
  ai_usage: "AI Usage", custom_sql: "Custom SQL",
};

function StatusBadge({ status }) {
  const map = {
    ready:      "bg-emerald-50 text-emerald-700",
    generating: "bg-blue-50 text-blue-700",
    failed:     "bg-red-50 text-red-700",
    expired:    "bg-gray-100 text-gray-500",
  };
  return (
    <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium ${map[status] || map.expired}`}>
      {status === "generating" && <Loader2 className="h-2.5 w-2.5 animate-spin" />}
      {status === "failed" && <AlertCircle className="h-2.5 w-2.5" />}
      {status.charAt(0).toUpperCase() + status.slice(1)}
    </span>
  );
}

function FormatBadge({ fmt }) {
  return fmt === "pdf"
    ? <span className="inline-flex items-center gap-1 rounded px-1.5 py-0.5 text-xs font-medium bg-red-50 text-red-600"><FileText className="h-3 w-3" />PDF</span>
    : <span className="inline-flex items-center gap-1 rounded px-1.5 py-0.5 text-xs font-medium bg-green-50 text-green-700"><FileSpreadsheet className="h-3 w-3" />CSV</span>;
}

export default function ReportHistoryTable({ reports, isLoading, onDownload, onDelete, currentUser, downloadingId }) {
  const [typeFilter, setTypeFilter] = useState("");
  const [fmtFilter, setFmtFilter] = useState("");
  const [confirmDelete, setConfirmDelete] = useState(null);

  const filtered = (reports || []).filter((r) => {
    if (typeFilter && r.report_type !== typeFilter) return false;
    if (fmtFilter && r.output_format !== fmtFilter) return false;
    return true;
  });

  const isExpiringSoon = (r) => {
    if (!r.expires_at) return false;
    return new Date(r.expires_at) - Date.now() < 86400000;
  };

  if (isLoading) {
    return (
      <div className="space-y-3">
        {[...Array(5)].map((_, i) => (
          <div key={i} className="h-12 rounded-lg bg-gray-100 animate-pulse" />
        ))}
      </div>
    );
  }

  return (
    <div>
      {/* Filters */}
      <div className="flex flex-wrap items-center gap-3 mb-4">
        <select value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}
          className="rounded-lg border border-gray-200 px-3 py-1.5 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500">
          <option value="">All Types</option>
          {Object.entries(TYPE_LABELS).map(([v, l]) => <option key={v} value={v}>{l}</option>)}
        </select>
        <div className="flex gap-1 rounded-lg border border-gray-200 p-0.5">
          {["", "pdf", "csv"].map((v) => (
            <button key={v} onClick={() => setFmtFilter(v)}
              className={`px-3 py-1 rounded-md text-xs font-medium transition-colors ${fmtFilter === v ? "bg-blue-600 text-white" : "text-gray-600 hover:bg-gray-100"}`}>
              {v === "" ? "All" : v.toUpperCase()}
            </button>
          ))}
        </div>
        <span className="ml-auto text-xs text-gray-400">{filtered.length} report{filtered.length !== 1 ? "s" : ""}</span>
      </div>

      {filtered.length === 0 ? (
        <div className="text-center py-16 text-gray-400">
          <FileText className="h-10 w-10 mx-auto mb-3 opacity-30" />
          <p className="text-sm">No reports generated yet. Generate your first report above.</p>
        </div>
      ) : (
        <div className="overflow-x-auto rounded-xl border border-gray-200">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 text-xs text-gray-500 uppercase tracking-wide">
              <tr>
                {["Report Name", "Type", "Format", "Period", "Size", "Status", "Generated By", "Date", ""].map((h) => (
                  <th key={h} className="px-4 py-3 text-left font-medium">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {filtered.map((r) => (
                <tr key={r.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-4 py-3 font-medium text-gray-900 max-w-[200px] truncate">
                    {r.report_name}
                    {isExpiringSoon(r) && r.status === "ready" && (
                      <span className="ml-1.5 text-xs font-medium text-orange-600 bg-orange-50 px-1.5 py-0.5 rounded">Expires soon</span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-gray-500">{TYPE_LABELS[r.report_type] || r.report_type}</td>
                  <td className="px-4 py-3"><FormatBadge fmt={r.output_format} /></td>
                  <td className="px-4 py-3 text-gray-500 whitespace-nowrap text-xs">
                    {r.date_range_start && `${r.date_range_start} → ${r.date_range_end}`}
                  </td>
                  <td className="px-4 py-3 text-gray-500 whitespace-nowrap">{formatFileSize(r.file_size_bytes)}</td>
                  <td className="px-4 py-3"><StatusBadge status={r.status} /></td>
                  <td className="px-4 py-3 text-gray-500">{r.generated_by_name || "—"}</td>
                  <td className="px-4 py-3 text-gray-400 whitespace-nowrap">{formatRelativeTime(r.generated_at)}</td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-1.5">
                      <button
                        onClick={() => onDownload(r)}
                        disabled={r.status !== "ready" || downloadingId === r.id}
                        title="Download"
                        className="p-1.5 rounded-lg hover:bg-blue-50 text-blue-600 disabled:text-gray-300 disabled:cursor-not-allowed transition-colors"
                      >
                        {downloadingId === r.id ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
                      </button>
                      {(currentUser?.role === "admin" || r.generated_by_name === currentUser?.full_name) && (
                        confirmDelete === r.id ? (
                          <div className="flex gap-1">
                            <button onClick={() => { onDelete(r.id); setConfirmDelete(null); }} className="text-xs text-red-600 font-medium hover:underline">Yes</button>
                            <button onClick={() => setConfirmDelete(null)} className="text-xs text-gray-500 hover:underline">No</button>
                          </div>
                        ) : (
                          <button onClick={() => setConfirmDelete(r.id)} title="Delete" className="p-1.5 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-500 transition-colors">
                            <Trash2 className="h-4 w-4" />
                          </button>
                        )
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
